name: aggregate
on:
  workflow_dispatch:
    inputs:
      projectName:
        description: 'Project Name'
        required: true
        default: 'books'
      companyName:
        description: 'Company Name'
        required: true
        default: 'sony'
      parameters:
       description: 'Parameters'
       required: true
env:
  CLOUD: true
jobs:
  aggregator:
    runs-on: ubuntu-latest
    steps:
      - name: Install xmllint
        run: |
           sudo apt update
           sudo apt-get install libpangocairo-1.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 gconf2 libasound2 libatk1.0-0 libgtk-3-0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
         cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS...
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-v1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install apify-cli
        run: 'npm install -g apify-cli'
      - name: Install dependencies
        run: 'npm install'
      - name: aggregation step
        id: collection
        run: parameters="${{github.event.inputs.parameters}}"  node index.js



